### ISSUE TITLE
Se puede abreviar

### ISSUE THREAD

**Issue by evolentini** [FelipeSarche/TP3TESTING#2]
Las dos lineas:
https://github.com/FelipeSarche/TP3TESTING/blob/556da923d2dfd7e3f636fb3949d5416a6bc04aab/test/test_leds.c#L78-L79
se podrían abreviar como:

```TEST_ASSERT_TRUE(LedState(12)); ```

trabajar menos siempre esta bueno :)

**Comment by FelipeIot** [comment]
resuelto
