### ISSUE TITLE
Otra forma de escribirlo

### ISSUE THREAD

**Issue by evolentini** [FelipeSarche/TP3TESTING#3]
Yo personalmente hubiese llamado a LedAllOn en lugar de escribir la variable, pero no esta mal en lo absoluto.

https://github.com/FelipeSarche/TP3TESTING/blob/556da923d2dfd7e3f636fb3949d5416a6bc04aab/test/test_leds.c#L69

**Comment by FelipeIot** [comment]
resuelto
